version: 2

jobs:
  build:
    docker:
      - image: circleci/node:12.12.0
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
      - run: 'yarn install'
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: 'yarn run ci'
