#!/usr/bin/env sh
set -e

# Build inline source
node -r esm ./scripts/pre-build.js

# Commit it (if present)
git add ./lib/source.js
git diff --quiet --staged || git commit -v -m "chore(source): Add stringified source"

# Build the final module
aberlaas build "$@"
